# Generated by Django 4.2.3 on 2023-07-26 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
